### ISSUE TITLE
[Invalid] Can't seem to get it to work. 

### ISSUE THREAD

**Issue by Loukious** [YouCanAi/LyricsGetterExt#6]
Both lyrics getter and StatusBar lyric installed and configured correctly. Lyrics getter ext also installed and given proper permissions. When I play a song on Spotify nothing happens.

**Comment by YouCanAi** [comment]
Can you give the notification that is displayed when it is played, there is still a problem with the bailout of this project, it is logical that an empty notification should appear if LyricsGetterExt is running properly, like this
![Screenshot_2023-10-20-11-02-00-571_statusbar find](https://github.com/VictorModi/LyricsGetterExt/assets/60372300/8fe19ab5-26ca-47d5-bbc6-ceb0b803a9f8)

**Comment by YouCanAi** [comment]
There are many reasons why it can't be displayed, such as StatusBarLyric doesn't have a normal Hook, LyricsGetterExt is killed by the system, lyrics are not found, etc. If it's possible can you try to put LyricsGetterExt into priv-app to ensure that LyricsGetterExt's service is working properly, ~~or Install a SQLite to see if LyricsGetterExt's Lyrics.db has lyrics for the current song.~~

Since the service is still not working properly for a long time, most of the time you need to grant Allow Notification Access to the LyricsGetterExt service again to make it work for a while.

Translated with www.DeepL.com/Translator (free version)

**Comment by Loukious** [comment]
> Can you give the notification that is displayed when it is played, there is still a problem with the bailout of this project, it is logical that an empty notification should appear if LyricsGetterExt is running properly, like this ![Screenshot_2023-10-20-11-02-00-571_statusbar find](https://user-images.githubusercontent.com/60372300/276806684-8fe19ab5-26ca-47d5-bbc6-ceb0b803a9f8.jpg)

I do indeed sometimes (but not always) get that notification. But it seems like the issue is from lyrics getter itself other than this. Do you have any idea if android 13 is supported? I suspect that something might have changed in the media events which stopping lyrics getter from detecting when music is playing.

**Comment by Loukious** [comment]
I also have this crash. Not sure if it's related.
![Screenshot_20231020-091752_AppErrorsTracking](https://github.com/VictorModi/LyricsGetterExt/assets/24696530/f3ca8e7c-c7d5-4b30-9d1d-a627bc5c9b67)

**Comment by YouCanAi** [comment]
> I also have this crash. Not sure if it's related. ![Screenshot_20231020-091752_AppErrorsTracking](https://user-images.githubusercontent.com/24696530/276868261-f3ca8e7c-c7d5-4b30-9d1d-a627bc5c9b67.png)

I can assure you that Android 13 is supported. As my device is also Android 13!

As well as that you might want to try uninstalling the current LyricsGetterExt installed on your device try using the latest build of https://github.com/VictorModi/LyricsGetterExt/actions to try and see if it works!

The crash you're reporting has been fixed in the Action(CI) version!

**Comment by Loukious** [comment]
> > I also have this crash. Not sure if it's related. ![Screenshot_20231020-091752_AppErrorsTracking](https://user-images.githubusercontent.com/24696530/276868261-f3ca8e7c-c7d5-4b30-9d1d-a627bc5c9b67.png)
> 
> I can assure you that Android 13 is supported. As my device is also Android 13!
> 
> As well as that you might want to try uninstalling the current LyricsGetterExt installed on your device try using the latest build of https://github.com/VictorModi/LyricsGetterExt/actions to try and see if it works!
> 
> The crash you're reporting has been fixed in the Action(CI) version!

Okay so I found this option 
![Screenshot_20231021-025036_Settings](https://github.com/VictorModi/LyricsGetterExt/assets/24696530/784c3ae5-1e1b-49ba-a371-047233b03944)
"Pin media player" seems with this option on the media events aren't caught correctly by Lyrics Getter Ext. Disabling it made it more consistent and correctly launching when playing a song. I found also the lyrics db file you told me about and it seems like it's getting the lyrics correctly. Problem is, Lyrics Getter is still not showing any lyrics in my status bar even though status bar lyric's test worked fine. You can close this as the issue is related to Lyrics Getter not this module.

**Comment by YouCanAi** [comment]
Looks like you've found the problem, thanks a lot for the feedback!

**Comment by YouCanAi** [comment]
I opened this issues by mistake, sorry. :(
